name: Auto approve model hash updates
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: src/config.yaml
      # If we filter out any non-config.yaml files, we do not
      # approve the PR, otherwise we auto approve it.
      - uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
        if: !env.GIT_DIFF_FILTERED
