name: Auto approve model hash updates
on: pull_request
jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.running.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: src/config.yaml
      - id: running
        run: echo "test=${{ env.GIT_DIFF_FILTERED }}" >> "$GITHUB_OUTPUT"
  auto-approve:
    runs-on: ubuntu-latest
    needs: diff
    steps:
      - uses: juliangruber/approve-pull-request-action@v2.0.0
        if: ${{ needs.diff.outputs.output }} != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
