name: Auto approve model hash updates
on: pull_request
jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.running.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: src/config.yaml
  auto-approve:
    runs-on: ubuntu-latest
    needs: diff
    steps:
      - uses: juliangruber/approve-pull-request-action@v2.0.0
        if: ${{ env.GIT_DIFF_FILTERED != '' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
